import '@/app/globals.css'
import Bottombar from '@/components/shared/Bottombar'
import Leftsidebar from '@/components/shared/Leftsidebar'
import Topbar from '@/components/shared/Topbar'
import Leftsidebartwo from '@/components/shared/leftsidebar2'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Topbar />
        <div className='flex '>
          <Leftsidebar />
          <Leftsidebartwo />
          <section className='main-container'>
            <div className='w-full max-w-4xl'>
              {children}
            </div>
          </section>
        </div>
        <Bottombar/>
      </body>
    </html>
  )
}
